# Generated by Django 4.1.7 on 2023-03-11 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newpaper', '0002_rename_user_author_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_user',
            new_name='user',
        ),
    ]
